In [59]:
#adding numpy
import numpy as np
n1 = np.array([10,20,30,40])
n1=n1+1
n1

array([11, 21, 31, 41])

In [60]:
#subtracting in numpy
n1=np.array([10,20,30,40])
n1=n1-2
n1

array([ 8, 18, 28, 38])

In [62]:
#multiplication of numpy
n1=np.array([10,20,30,40])
n1=n1*2
n1

array([20, 40, 60, 80])

In [63]:
#division in numpy
n1=np.array([10,20,30,40])
n1=n1/2
n1

array([ 5., 10., 15., 20.])